name: Nest Video Downloader
version: "0.2.2"
slug: nest_downloader
description: Download videos from Nest cameras
url: https://github.com/gabrielgbim/ha-addons/tree/main/nest_downloader
arch:
  - aarch64
  - amd64
init: false
options:
  BASE_PATH: "/media"
  GOOGLE_USERNAME: ""
  GOOGLE_MASTER_TOKEN: ""
  LOCAL_TIMEZONE: "America/New_York"
  REFRESH_INTERVAL: 10
schema:
  BASE_PATH: str
  GOOGLE_USERNAME: email
  GOOGLE_MASTER_TOKEN: password
  LOCAL_TIMEZONE: str
  REFRESH_INTERVAL: int
image: ghcr.io/gabrielgbim/nest-downloader-{arch}
